--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.435.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26/11/2020 19:19:02
-- Server version: 10.4.6
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO despacho.personal(pe_id, pe_lp, pe_dni, pe_nombre, pe_apellido, pe_domicilio, pe_provincia, pe_telefono, pe_fecha_alta) VALUES
(1, 324, 234, 'alcides', 'quinteros', 'godoy 677', 'caba', 2343, '2020-11-01'),
(2, 244, 234234, 'licencia', 'asd', 'gad 43', 'caba', 3423423, '2020-11-05');